#!/bin/sh

set -e

tcrm_CONFIGURATION_FILE=/etc/tcrm/tcrm.conf
tcrm_GROUP="tcrm"
tcrm_DATA_DIR=/var/lib/tcrm
tcrm_LOG_DIR=/var/log/tcrm
tcrm_USER="tcrm"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^tcrm:"; then
            adduser --system --home $tcrm_DATA_DIR --quiet --group $tcrm_USER
            # Data dir
            chown $tcrm_USER:$tcrm_GROUP $tcrm_DATA_DIR
        fi
        # Register "$tcrm_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $tcrm_USER" 2> /dev/null || true
        # Configuration file
        chown $tcrm_USER:$tcrm_GROUP $tcrm_CONFIGURATION_FILE
        chmod 0640 $tcrm_CONFIGURATION_FILE
        # Log
        mkdir -p $tcrm_LOG_DIR
        chown $tcrm_USER:$tcrm_GROUP $tcrm_LOG_DIR
        chmod 0750 $tcrm_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-tcrm-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
