#!/bin/sh

set -e

tcrm_LIB_DIR=/var/lib/tcrm
tcrm_USER="tcrm"
tcrm_GROUP="tcrm"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $tcrm_USER || true
        delgroup --quiet --system --only-if-empty $tcrm_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-tcrm-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$tcrm_LIB_DIR" ]; then
            rm -rf $tcrm_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
